import type { Category, Prompt } from "./types";

export const seedCategories: Category[] = [
  {
    id: "cat-writing",
    name: "Writing",
    description: "Creative writing and copy assets",
    color: "violet",
    icon: "PenLine",
  },
  {
    id: "cat-code",
    name: "Code Generation",
    description: "Snippets, refactors, and reviews",
    color: "cyan",
    icon: "Terminal",
  },
  {
    id: "cat-marketing",
    name: "Marketing",
    description: "Campaigns, ads, and positioning",
    color: "amber",
    icon: "Megaphone",
  },
  {
    id: "cat-data",
    name: "Data Analysis",
    description: "Summaries, insights, and reports",
    color: "emerald",
    icon: "BarChart3",
  },
  {
    id: "cat-support",
    name: "Customer Support",
    description: "Replies, macros, and de-escalation",
    color: "rose",
    icon: "Headset",
  },
  {
    id: "cat-brainstorm",
    name: "Brainstorming",
    description: "Idea generation and exploration",
    color: "indigo",
    icon: "Lightbulb",
  },
  {
    id: "cat-research",
    name: "Research",
    description: "Deep dives and literature reviews",
    color: "sky",
    icon: "Search",
  },
  {
    id: "cat-product",
    name: "Product",
    description: "Specs, user stories, and roadmaps",
    color: "orange",
    icon: "Package",
  },
];

const now = new Date();
const daysAgo = (n: number) => new Date(now.getTime() - n * 86400000).toISOString();

export const seedPrompts: Prompt[] = [
  {
    id: "p-blog-outline",
    title: "Blog Post Outline Generator",
    content:
      "Create a detailed SEO-optimized outline for a blog post about {{topic}}. Use a {{tone}} tone and aim for approximately {{word_count}} words. Include a punchy headline, a compelling introduction hook, 5 key subheaders with 2-3 bullet points each, and a conclusion with a call to action.",
    categoryId: "cat-writing",
    tags: ["content", "seo", "outline"],
    favorite: true,
    model: "GPT-4 Turbo",
    temperature: 0.7,
    maxTokens: 2000,
    visibility: "private",
    variableNotes: {
      topic: "The subject of the blog post.",
      tone: "Desired writing style, e.g. conversational, authoritative, playful.",
      word_count: "Target length of the finished post.",
    },
    notes:
      "Works best with GPT-4. Provide specific keywords in the topic for better SEO targeting.",
    createdAt: daysAgo(90),
    updatedAt: daysAgo(2),
    timesUsed: 42,
    lastUsedAt: daysAgo(2),
  },
  {
    id: "p-code-review",
    title: "Senior Code Reviewer",
    content:
      "Act as a senior {{language}} engineer reviewing a pull request. Review the following code for correctness, security, and readability:\n\n{{code}}\n\nList issues in order of severity, explain the risk of each, and suggest a concrete fix.",
    categoryId: "cat-code",
    tags: ["review", "quality", "security"],
    favorite: true,
    model: "Claude 4.5 Opus",
    temperature: 0.2,
    maxTokens: 3000,
    visibility: "team",
    variableNotes: {
      language: "Primary programming language of the code.",
      code: "The code snippet or diff to review.",
    },
    notes: "Pair with a low temperature for consistent, less creative reviews.",
    createdAt: daysAgo(60),
    updatedAt: daysAgo(5),
    timesUsed: 78,
    lastUsedAt: daysAgo(1),
  },
  {
    id: "p-ad-copy",
    title: "Performance Ad Copy Variations",
    content:
      "Write 5 short performance-marketing ad variations for {{product}} targeting {{audience}}. Each variation should be under 30 words, highlight a distinct benefit, and end with a clear call to action. Match a {{tone}} tone.",
    categoryId: "cat-marketing",
    tags: ["ads", "copywriting", "conversion"],
    favorite: false,
    model: "GPT-4o",
    temperature: 0.9,
    maxTokens: 800,
    visibility: "team",
    variableNotes: {
      product: "The product or service being advertised.",
      audience: "Who the ad is targeting.",
      tone: "Voice of the copy, e.g. bold, friendly, urgent.",
    },
    notes: "Generate in batches and A/B test the top 2-3 variations.",
    createdAt: daysAgo(45),
    updatedAt: daysAgo(10),
    timesUsed: 31,
    lastUsedAt: daysAgo(4),
  },
  {
    id: "p-data-summary",
    title: "Dataset Insight Summarizer",
    content:
      "You are a data analyst. Given the dataset description below, identify the top 3 trends, 2 anomalies worth investigating, and one actionable recommendation.\n\nDataset: {{dataset_description}}\nTime range: {{time_range}}",
    categoryId: "cat-data",
    tags: ["analytics", "reporting", "summary"],
    favorite: false,
    model: "Gemini 2.5 Pro",
    temperature: 0.3,
    maxTokens: 1500,
    visibility: "private",
    variableNotes: {
      dataset_description: "A short description of the data's columns and source.",
      time_range: "The period the data covers.",
    },
    notes: "Attach sample rows for more grounded, specific insights.",
    createdAt: daysAgo(30),
    updatedAt: daysAgo(15),
    timesUsed: 19,
    lastUsedAt: daysAgo(6),
  },
  {
    id: "p-support-reply",
    title: "Empathetic Support Reply",
    content:
      "A customer wrote: \"{{customer_message}}\"\n\nWrite a helpful, empathetic support reply. Acknowledge their frustration, explain {{resolution}} clearly, and offer a next step. Keep it under 120 words and avoid corporate jargon.",
    categoryId: "cat-support",
    tags: ["support", "tone", "templates"],
    favorite: true,
    model: "Claude 4.5 Sonnet",
    temperature: 0.5,
    maxTokens: 600,
    visibility: "team",
    variableNotes: {
      customer_message: "The original message from the customer.",
      resolution: "The fix, refund, or workaround being offered.",
    },
    notes: "Great as a first draft — always review before sending.",
    createdAt: daysAgo(70),
    updatedAt: daysAgo(3),
    timesUsed: 64,
    lastUsedAt: daysAgo(1),
  },
  {
    id: "p-brainstorm-names",
    title: "Product Name Brainstormer",
    content:
      "Brainstorm 15 name ideas for a {{product_type}} aimed at {{audience}}. Mix short punchy names, compound words, and metaphor-based names. For each, add a one-line rationale.",
    categoryId: "cat-brainstorm",
    tags: ["naming", "ideation"],
    favorite: false,
    model: "GPT-4o",
    temperature: 1.0,
    maxTokens: 1200,
    visibility: "private",
    variableNotes: {
      product_type: "What kind of product or feature this is.",
      audience: "Who the product is for.",
    },
    notes: "Push temperature higher for more unusual, memorable options.",
    createdAt: daysAgo(20),
    updatedAt: daysAgo(20),
    timesUsed: 8,
    lastUsedAt: daysAgo(12),
  },
  {
    id: "p-research-lit",
    title: "Literature Review Synthesizer",
    content:
      "Summarize the key findings across these sources on {{research_topic}}: {{sources}}. Group findings by theme, note any contradictions between sources, and flag open questions for further research.",
    categoryId: "cat-research",
    tags: ["research", "synthesis"],
    favorite: false,
    model: "Claude 4.5 Opus",
    temperature: 0.3,
    maxTokens: 2500,
    visibility: "private",
    variableNotes: {
      research_topic: "The overarching subject being researched.",
      sources: "Titles, abstracts, or links to the source material.",
    },
    notes: "Best with primary sources pasted in full rather than summaries.",
    createdAt: daysAgo(15),
    updatedAt: daysAgo(15),
    timesUsed: 5,
    lastUsedAt: daysAgo(15),
  },
  {
    id: "p-user-story",
    title: "User Story Writer",
    content:
      "Write a user story and acceptance criteria for the following feature request: {{feature_request}}. Use the format 'As a {{user_type}}, I want..., so that...' and include 3-5 testable acceptance criteria.",
    categoryId: "cat-product",
    tags: ["specs", "agile", "planning"],
    favorite: true,
    model: "GPT-4 Turbo",
    temperature: 0.4,
    maxTokens: 900,
    visibility: "team",
    variableNotes: {
      feature_request: "The raw feature idea or request to formalize.",
      user_type: "The persona this story is written from.",
    },
    notes: "Feed directly into your ticketing tool once reviewed.",
    createdAt: daysAgo(25),
    updatedAt: daysAgo(7),
    timesUsed: 27,
    lastUsedAt: daysAgo(2),
  },
  {
    id: "p-cold-email",
    title: "Cold Outreach Email",
    content:
      "Write a short cold outreach email to {{recipient_role}} at {{company}}. Reference {{relevant_trigger}}, keep it under 100 words, and end with a low-friction call to action for a 15-minute call.",
    categoryId: "cat-marketing",
    tags: ["sales", "email", "outreach"],
    favorite: false,
    model: "GPT-4o",
    temperature: 0.7,
    maxTokens: 500,
    visibility: "team",
    variableNotes: {
      recipient_role: "The job title of the person you're emailing.",
      company: "The recipient's company name.",
      relevant_trigger: "A recent news item or signal that makes this timely.",
    },
    notes: "Always personalize the trigger — generic ones hurt reply rates.",
    createdAt: daysAgo(40),
    updatedAt: daysAgo(9),
    timesUsed: 53,
    lastUsedAt: daysAgo(3),
  },
  {
    id: "p-sql-explain",
    title: "SQL Query Explainer",
    content:
      "Explain what the following SQL query does in plain English, step by step, and suggest one optimization if applicable:\n\n{{sql_query}}",
    categoryId: "cat-code",
    tags: ["sql", "documentation"],
    favorite: false,
    model: "GPT-4 Turbo",
    temperature: 0.2,
    maxTokens: 700,
    visibility: "private",
    variableNotes: {
      sql_query: "The SQL statement to explain.",
    },
    notes: "Include the table schema for more accurate optimization tips.",
    createdAt: daysAgo(12),
    updatedAt: daysAgo(12),
    timesUsed: 14,
    lastUsedAt: daysAgo(8),
  },
  {
    id: "p-meeting-notes",
    title: "Meeting Notes to Action Items",
    content:
      "Convert these raw meeting notes into a clean summary with sections for Decisions, Action Items (with owner and due date if mentioned), and Open Questions:\n\n{{raw_notes}}",
    categoryId: "cat-product",
    tags: ["productivity", "meetings"],
    favorite: true,
    model: "Gemini 2.5 Pro",
    temperature: 0.3,
    maxTokens: 1000,
    visibility: "team",
    variableNotes: {
      raw_notes: "Unstructured notes or a transcript from the meeting.",
    },
    notes: "Works well pasted straight from a transcription tool.",
    createdAt: daysAgo(5),
    updatedAt: daysAgo(1),
    timesUsed: 22,
    lastUsedAt: daysAgo(0),
  },
];
